automation.qmetry.enabled = true
automation.qmetry.debug = true
automation.qmetry.url=https://qtmcloud.qmetry.com/rest/api/automation/importresult 
automation.qmetry.apikey =e45701d5681b25a7bb2a37032fe1b260c277b3128e573114f6d4dc16d6e0e95ca272ad61c63465c99113b9623b717f540d31ba9fda27f438e46da300955a08cc85505ebd9cb89ef7eacec1259f9a78ef
automation.qmetry.filepath=test-output/cucumber.json
#automation.qmetry.environment=Google Chrome
#automation.qmetry.build=1.0
automation.qmetry.attachfile=true
#automation.qmetry.testcase.labels=l1,l2,l3
#automation.qmetry.testcase.components=c1,c2
automation.qmetry.testcase.priority=Medium
automation.qmetry.testcase.status=In Progress
#automation.qmetry.testcase.sprintId=34534
#automation.qmetry.testcase.fixVersionId=35345
automation.qmetry.testcase.folderId=2013252
automation.qmetry.testcase.description=Test Case description
automation.qmetry.testcase.precondition=Test Case precondition
#automation.qmetry.testcase.assignee={Valid User Account Id}
#automation.qmetry.testcase.reporter={Valid User Account Id}

#automation.qmetry.testcase.customFields=[{"name" : "custom field 1", "value": "high,medium,low"},{"name" : "custom field 2", "value": 10.12}]
automation.qmetry.testCaseExecution.comment = Test Case Execution Comment
#automation.qmetry.testCaseExecution.actualTime = 10:10:10
#automation.qmetry.testCaseExecution.executionPlannedDate = 16/Feb/2024
#automation.qmetry.testCaseExecution.assignee = {Valid User Account Key}
#automation.qmetry.testCaseExecution.customFields=[{"name" : "custom field 1", "value": "high,medium,low"},{"name" : "custom field 2", "value": 10.12}]