automation.qmetry.enabled = true
automation.qmetry.debug = true
automation.qmetry.url=https://qtmcloud.qmetry.com/rest/api/automation/importresult 
automation.qmetry.apikey =47d2156a39547200d346544c5e98da455741f25f5fda6e7c7a1748160066e2550940939f295665d5343ecbbe8efde81079ddc54a30ac7b78587d4c44cc0b94a1c8e3c57ba90c2aa327ec59ae59af0b2b
automation.qmetry.filepath=test-output/cucumber.json
automation.qmetry.environment=Google Chrome
automation.qmetry.build=1.0
automation.qmetry.attachfile=true
automation.qmetry.matchTestSteps=true
automation.qmetry.testCycleToReuse=NR-TR-1
automation.qmetry.testcycle.summary=Test Cycle summary
automation.qmetry.testcycle.labels=l1,l2,l3
automation.qmetry.testcycle.components=c1,c2,c3
automation.qmetry.testcycle.priority=High
automation.qmetry.testcycle.status=To Do
automation.qmetry.testcycle.sprintId=1242
#automation.qmetry.testcycle.fixVersionId=14234
automation.qmetry.testcycle.folderId=2013253
automation.qmetry.testcycle.description=Test Cycle description
automation.qmetry.testcycle.assignee={Valid User Account Id}
automation.qmetry.testcycle.reporter={Valid User Account Id}
automation.qmetry.testcycle.plannedStartDate=15/May/2020 00:00
automation.qmetry.testcycle.plannedEndDate=30/May/2020 00:00
automation.qmetry.testcycle.customFields=[{"name" : "custom field 1", "value": "high,medium,low"},{"name" : "custom field 2", "value": "29/May/2020"}]
automation.qmetry.testcase.labels=l1,l2,l3
automation.qmetry.testcase.components=c1,c2
automation.qmetry.testcase.priority=Medium
automation.qmetry.testcase.status=In Progress
automation.qmetry.testcase.sprintId=34534
#automation.qmetry.testcase.fixVersionId=35345
automation.qmetry.testcase.folderId=2013252
automation.qmetry.testcase.description=Test Case description
automation.qmetry.testcase.precondition=Test Case precondition
automation.qmetry.testcase.assignee={Valid User Account Id}
automation.qmetry.testcase.reporter={Valid User Account Id}
automation.qmetry.testcase.estimatedTime=10:10:10
automation.qmetry.testcase.customFields=[{"name" : "custom field 1", "value": "high,medium,low"},{"name" : "custom field 2", "value": 10.12}]
automation.qmetry.testCaseExecution.comment = Test Case Execution Comment
automation.qmetry.testCaseExecution.actualTime = 10:10:10
automation.qmetry.testCaseExecution.executionPlannedDate = 16/Feb/2024
automation.qmetry.testCaseExecution.assignee = {Valid User Account Key}
automation.qmetry.testCaseExecution.customFields=[{"name" : "custom field 1", "value": "high,medium,low"},{"name" : "custom field 2", "value": 10.12}]